### PR TITLE
Blur

### PR DESCRIPTION
**Pull request by ErikReider**
Fixes: #14 

Note: The blur isn't correctly aligned but should™ be easily fixed

TODO:
- [x] Add global config options (per surface blur won't work due to the damage calculations)
- [x] Extend the damage (fixing artifacts)
- [ ] Blit the old region to remove artifacts
- [x] Fix blur not rendering correctly
- [x] Add tinywl example
- [ ] Refactor/simplify `fx_texture` code?
- [ ] Add "optimized" blur

### CODE REVIEW

**Comment by WillPower3309** [comment]
Is optimized blur in? Haven't looked through yet but it'd be a TODO if not

**Comment by WillPower3309** [comment]
I'll try to rebase our renderer off of wlr_renderer to simplify things with buffers and textures here

**Comment by ErikReider** [comment]
> Is optimized blur in? Haven't looked through yet but it'd be a TODO if not

Added in the todo :)

**Comment by ErikReider** [comment]
Superseded by #30

**Pull request closed without merging**
