### PR TITLE
Meson fixes

### PR DESCRIPTION
**Pull request by ErikReider**
Fixes: #26 

Todo:
- [x] Add back xkbcommon dep
- [x] Move some headers into `scenefx` dir
	- [x] Shadow struct
	- [x] custom wlr_scene struct
	- [x] All of the fx_renderer/pass headers?
- [x] Fix not being able to build statically due to conflicting functions

### CODE REVIEW

**Comment by ErikReider** [comment]
I've tested it and everything works as expected, even installed it as a library on my system :)

The only question mark is how we're going to expose the fx_renderer. Everything in the renderer is exposed atm which might not be ideal. Could be useful for SwayFX though?

Any input?

**Comment by WillPower3309** [comment]
> I've tested it and everything works as expected, even installed it as a library on my system :)
> 
> The only question mark is how we're going to expose the fx_renderer. Everything in the renderer is exposed atm which might not be ideal. Could be useful for SwayFX though?
> 
> Any input?

Discussed on discord but mentioning here too for anyone following the issue on GitHub, for now we will be exposing the bare minimum functions for SwayFX to use. We can always expose more functions but can't take them away (without annoying our users) so we're starting small.

**Comment by ErikReider** [comment]
Should be ready now

**Comment by ErikReider** [comment]
I wonder if we could remove our own declaration of `struct wlr_scene_*` and just rename the only necessary function names to fx_*? I'll investigate...

**Review by WillPower3309 — APPROVED** [review]

**Comment by lidgnulinux** [comment]
For the example tinywl, I think the Makefile need little additional : 
```
$(shell pkg-config --cflags --libs scenefx) 
```

**Pull request merged**
